### PR TITLE
Refactor useRotate

### PR DESCRIPTION
**Pull request by codemilli**
Declare useRef value inside useRotate hooks for preventing from redeclare every uses.

### CODE REVIEW

**Comment by UYEONG** [comment]
Oh.. Nice pattern! please apply to useRollerCoaster of Audio, useWave of Puff, useBlinking of Spinning too!

**Comment by codemilli** [comment]
@UYEONG Please check it out

**Comment by UYEONG** [comment]
Thank you!

**Comment by UYEONG** [comment]
@codemilli Please change branch to master.

**Comment by codemilli** [comment]
@UYEONG please check #14

**Pull request closed without merging**
